# Generated by Django 5.0.3 on 2024-04-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('barcode', models.PositiveIntegerField(verbose_name='barcode')),
                ('id_code', models.PositiveIntegerField(verbose_name='ID code')),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3, verbose_name='currency')),
                ('purchasing_price', models.FloatField(verbose_name='purchasing price')),
                ('markup_percentage', models.PositiveSmallIntegerField(verbose_name='markup percentage')),
                ('selling_price', models.FloatField(verbose_name='selling price')),
                ('wholesale_price', models.FloatField(verbose_name='wholesale price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('purchasing_amount', models.PositiveIntegerField(verbose_name='purchasing amount')),
                ('selling_amount', models.PositiveIntegerField(verbose_name='selling amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'warehouse product',
                'verbose_name_plural': 'warehouse products',
                'db_table': 'warehouse_product',
                'ordering': ['-modified'],
            },
        ),
    ]
