# Generated by Django 5.0.3 on 2024-04-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('barcode', models.PositiveIntegerField(verbose_name='barcode')),
                ('id_code', models.PositiveIntegerField(verbose_name='ID code')),
                ('currency', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], max_length=3, verbose_name='currency')),
                ('purchasing_price', models.PositiveIntegerField(verbose_name='purchasing price')),
                ('extra_charge', models.PositiveSmallIntegerField(verbose_name='extra charge')),
                ('selling_price', models.PositiveIntegerField(verbose_name='selling price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
        ),
    ]
