# Generated by Django 5.0.4 on 2024-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.PositiveIntegerField(default=8245623),
            preserve_default=False,
        ),
    ]
