# Generated by Django 5.0.3 on 2024-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_warehouseproduct_id_alter_warehouseproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='purchasing_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='selling_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.FloatField(default=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='discount_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='total',
            field=models.FloatField(default=5000),
            preserve_default=False,
        ),
    ]
