# Generated by Django 5.0.3 on 2024-04-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('purchasing_price', models.PositiveIntegerField(verbose_name='purchasing price')),
                ('markup_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='extra charge')),
                ('selling_price', models.PositiveIntegerField(verbose_name='selling price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
        ),
    ]
