# Generated by Django 5.0.4 on 2024-04-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_markup_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=128, verbose_name='barcode'),
        ),
    ]
