# Generated by Django 5.0.3 on 2024-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_purchaseproduct_purchasing_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(default='Komron', max_length=128),
            preserve_default=False,
        ),
    ]
