# Generated by Django 5.0.3 on 2024-04-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-modified'], 'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
