# Generated by Django 5.0.3 on 2024-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_provider_user_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contract_number',
            field=models.PositiveIntegerField(default=2584345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='inn',
            field=models.PositiveIntegerField(default=52038489235234),
            preserve_default=False,
        ),
    ]
