# Generated by Django 5.0.3 on 2024-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_inventory_options_alter_inventory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
