# Generated by Django 5.0.3 on 2024-04-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_wholesale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.PositiveSmallIntegerField(verbose_name='extra charge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchasing_price',
            field=models.FloatField(verbose_name='purchasing price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(verbose_name='selling price'),
        ),
    ]
