# Generated by Django 5.0.3 on 2024-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_provider_contract_number_provider_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
