# Generated by Django 5.0.3 on 2024-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_purchase_left_purchase_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
