# Generated by Django 5.0.3 on 2024-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_purchasing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchasing_price',
            field=models.FloatField(verbose_name='purchasing price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(verbose_name='selling price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(),
        ),
    ]
