# Generated by Django 5.0.3 on 2024-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_purchasing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.PositiveSmallIntegerField(verbose_name='markup percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(verbose_name='wholesale price'),
        ),
    ]
