# Generated by Django 5.0.4 on 2024-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created',
            field=models.CharField(max_length=256, verbose_name='created time'),
        ),
    ]
