# Generated by Django 5.0.3 on 2024-04-23 16:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_purchase_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 23, 21, 9, 54, 335950)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.provider'),
            preserve_default=False,
        ),
    ]
