# Generated by Django 5.0.4 on 2024-04-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_markup_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('purchasing_amount', models.PositiveIntegerField(verbose_name='purchasing amount')),
                ('selling_amount', models.PositiveIntegerField(verbose_name='selling amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'warehouse product',
                'verbose_name_plural': 'warehouse products',
                'db_table': 'warehouse_product',
                'ordering': ['-modified'],
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
