# Generated by Django 5.0.3 on 2024-04-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_purchase_time_warehouseproduct_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created'], 'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 23, 21, 50, 2, 622148)),
            preserve_default=False,
        ),
    ]
