# Generated by Django 5.0.4 on 2024-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_purchase_options_payment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.PositiveIntegerField(max_length=256, null=True),
        ),
    ]
