# Generated by Django 5.0.3 on 2024-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Sobirov', max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
