# Generated by Django 5.0.3 on 2024-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='discount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='discount_price',
            field=models.FloatField(default=245),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='purchasing_amount',
            field=models.FloatField(verbose_name='purchasing amount'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='selling_amount',
            field=models.FloatField(verbose_name='selling amount'),
        ),
    ]
