# Generated by Django 5.0.3 on 2024-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_delete_magazine_warehouseproduct_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='purchasing_amount',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='selling_amount',
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='id_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
