# Generated by Django 5.0.4 on 2024-04-24 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('inn', models.PositiveIntegerField()),
                ('contract_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.CharField(max_length=256, verbose_name='created time')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=256, null=True)),
                ('invoice_number', models.PositiveIntegerField()),
                ('to_consignment', models.BooleanField()),
                ('total', models.FloatField()),
                ('paid', models.FloatField(default=0)),
                ('left', models.FloatField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.provider')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'db_table': 'purchase',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('discount', models.IntegerField()),
                ('discount_price', models.FloatField()),
                ('total', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                               to='purchase.purchase')),
            ],
            options={
                'verbose_name': 'purchase product',
                'verbose_name_plural': 'purchase products',
                'db_table': 'purchase_product',
                'ordering': ['-modified'],
            },
        ),
    ]
