# Generated by Django 5.0.3 on 2024-05-05 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.CharField(max_length=256, verbose_name='created time')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.PositiveIntegerField()),
                ('to_consignment', models.BooleanField()),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3, verbose_name='currency')),
                ('total', models.FloatField()),
                ('paid', models.FloatField(default=0)),
                ('left', models.FloatField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='warehouse.provider')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'db_table': 'purchase',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_product', to='warehouse.warehouseproduct')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchase.purchase')),
            ],
            options={
                'verbose_name': 'purchase product',
                'verbose_name_plural': 'purchase products',
                'db_table': 'purchase_product',
                'ordering': ['-modified'],
            },
        ),
    ]
