# Generated by Django 5.0.4 on 2024-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='currency'),
            preserve_default=False,
        ),
    ]
