# Generated by Django 5.0.3 on 2024-05-02 18:40

import django.db.models.deletion
from django.db import migrations, models

from apps.store.models import Store


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_currency'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(default=Store.objects.create(name='storeee').id, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
