# Generated by Django 5.0.3 on 2024-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='total',
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='id_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
