# Generated by Django 5.0.3 on 2024-04-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundproduct',
            old_name='warehouse_product',
            new_name='product',
        ),
    ]
