# Generated by Django 5.0.4 on 2024-04-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_rename_warehouse_product_refundproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundproduct',
            old_name='product',
            new_name='warehouse_product',
        ),
        migrations.RemoveField(
            model_name='refundproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='refundproduct',
            name='discount_price',
        ),
    ]
