# Generated by Django 5.0.4 on 2024-04-27 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0003_rename_product_refundproduct_warehouse_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refundproduct',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='refund.refund'),
        ),
    ]
