# Generated by Django 5.0.3 on 2024-05-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashier',
            old_name='cach',
            new_name='cash',
        ),
    ]
